









/*------------------------------------------------------------------------------
  <auto-generated>
       This code was generated by a T4 template.

       Changes to this file may cause incorrect behavior and will be lost if
       the code is regenerated.
  </auto-generated>
------------------------------------------------------------------------------*/

using System;
using System.Reflection;
using System.Runtime.InteropServices;
using SQRL;

[assembly: AssemblyCompany(AssemblyInfo.Company)]
[assembly: AssemblyProduct(AssemblyInfo.Product)]
[assembly: AssemblyTitle(AssemblyInfo.Title)]
[assembly: AssemblyCopyright(AssemblyInfo.Copyright)]
[assembly: AssemblyConfiguration(AssemblyInfo.Configuration)]
[assembly: ComVisible(false)][assembly: CLSCompliant(false)]
[assembly: AssemblyVersion(AssemblyInfo.Version)]
[assembly: AssemblyFileVersion(AssemblyInfo.FileVersion)]
[assembly: AssemblyInformationalVersion(AssemblyInfo.InformationalVersion)]



namespace SQRL {
	internal sealed partial class AssemblyInfo {
		 internal const string Company = "Harry Steinhilber, Jr.";
		 internal const string Product = "SQRL for Windows";
		 internal const string Title = "SQRL.Core";
		 internal const string Copyright = "Copyright ©2014 Harry Steinhilber, Jr.";
		 internal const string Trademark = "All rights reserved";
		 internal const string Configuration = "Debug";
		 internal const string Version = "0.1.0";
		 internal const string FileVersion = "0.1.0";
		 internal const string InformationalVersion = "0.1.0-e121ca3";
   
		 private AssemblyInfo() {
		 }
	}
}
